### ISSUE TITLE
Single URI for multiple fragments result in hash collision

### ISSUE THREAD

**Issue by pietercolpaert** [LinkedDataFragments/Client.js#31]
# Problem

A single URI for multiple fragments result in hash collision. The federated client assigns an “empty” label to a certain fragment, and therefore also to similar fragments.

## Reproduce

Example query that works:
http://client.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Flinkedgeodata;http%3A%2F%2Fpieter.pm%2Fparkingtest.ttl&query=SELECT%20*%20WHERE%20%7B%0A%20%20%20%20%3FsGent%20a%20%3Chttp%3A%2F%2Fvocab.datex.org%2Fterms%23UrbanParkingSite%3E%20%3B%0A%20%20%20%20%20%23%20%20%20%20%20%20%20%20%20%20%20%20%3Fp%20%3Fo%20.%0A%7D%20LIMIT%2020
Example query that does not work while it should:
http://client.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Flinkedgeodata;http%3A%2F%2Fpieter.pm%2Fparkingtest.ttl&query=SELECT%20*%20WHERE%20%7B%0A%20%20%20%20%3FsGent%20a%20%3Chttp%3A%2F%2Fvocab.datex.org%2Fterms%23UrbanParkingSite%3E%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fp%20%3Fo%20.%0A%7D%20LIMIT%2020

**Comment by RubenVerborgh** [comment]
The data in `http://pieter.pm/parkingtest.ttl` currently contains
```
<http://pieter.pm/parkingtest.ttl> void:count "200" .
```
but the [correct predicate](https://www.hydra-cg.com/spec/latest/triple-pattern-fragments/#definition) is `void:triples`. Fixing this yields the expected result.

The error is only triggered with a least two triple patterns, because this is when the count metadata is necessary for the correct join error.
