### ISSUE TITLE
First page requested twice on CONSTRUCT

### ISSUE THREAD

**Issue by barthanssens** [LinkedDataFragments/Client.js#32]
Not sure if this a client or server issue, but I've noticed that the demo on http://client.linkeddatafragments.org often (always ?) sends the initial request twice when the query is a CONSTRUCT / LIMIT

E.g. select source "DBpedia 2014", query for ten results using `CONSTRUCT WHERE { ?s ?p ?o. } LIMIT 10`,  execution log shows 
```
Requesting http://fragments.dbpedia.org/2014/en
Requesting http://fragments.dbpedia.org/2014/en 
```
If the limit is changed to, say, 1000, the following pages (?page=...) are only requested once

Is the client perhaps not aware that the first fragment already contains a paged result ?

**Comment by RubenVerborgh** [comment]
Hi @barthanssens, the first request is to discover the interface; the second request to get the data. Since in your example, the data is `?s ?p ?o`, those fragments are the same; with a more specific query, it will be different requests.

Note that the request will be cached anyway, so it will not actually be sent out twice.

**Comment by barthanssens** [comment]
Ok, thanks for the info
